CREATE TABLE public."Cinemas"
(
    "Row_Num" serial NOT NULL,
    "Cinema_Name" character varying(200) NOT NULL,
    "Halls_Count" integer NOT NULL,
    PRIMARY KEY ("Row_Num")
);

ALTER TABLE public."Cinemas"
    ADD CONSTRAINT "Unique_Name" UNIQUE ("Cinema_Name");


CREATE TABLE public."Halls"
(
    "Row_Num" serial NOT NULL,
    "Hall_Name" character varying(200) NOT NULL,
    "Cinema_RowID" integer NOT NULL,
    "Place_Status" bytea NOT NULL,
	"Place_Count" integer NOT NULL,
    PRIMARY KEY ("Row_Num"),
    CONSTRAINT "ROW_ID" FOREIGN KEY ("Cinema_RowID")
        REFERENCES public."Cinemas" ("Row_Num") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


INSERT INTO public."Cinemas"("Row_Num", "Cinema_Name", "Halls_Count")
	VALUES (1, 'Cinema1', 2);
INSERT INTO public."Cinemas"("Row_Num", "Cinema_Name", "Halls_Count")
	VALUES (2, 'Cinema2', 4);
INSERT INTO public."Cinemas"("Row_Num", "Cinema_Name", "Halls_Count")
	VALUES (3, 'Cinema3', 3);
INSERT INTO public."Cinemas"("Row_Num", "Cinema_Name", "Halls_Count")
	VALUES (4, 'Cinema4', 5);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (1, 'Hall1', 1, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (2, 'Hall2', 2, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (3, 'Hall3', 1, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (4, 'Hall4', 3, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (5, 'Hall5', 3, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (6, 'Hall6', 4, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (7, 'Hall7', 2, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (8, 'Hall8', 3, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (9, 'Hall9', 4, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (10, 'Hall10', 4, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (11, 'Hall11', 2, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (12, 'Hall12', 4, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (13, 'Hall13', 2, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);

INSERT INTO public."Halls"("Row_Num", "Hall_Name", "Cinema_RowID", "Place_Status", "Place_Count")
	VALUES (14, 'Hall14', 4, '{"places":[{"Row":1,"place":1,"free":true},{"Row":1,"place":2,"free":true},{"Row":1,"place":3,"free":true},{"Row":1,"place":4,"free":true},{"Row":1,"place":5,"free":true},{"Row":1,"place":6,"free":true},{"Row":1,"place":7,"free":true},{"Row":1,"place":8,"free":true},{"Row":1,"place":9,"free":true},{"Row":1,"place":10,"free":true},{"Row":2,"place":1,"free":true},{"Row":2,"place":2,"free":true},{"Row":2,"place":3,"free":true},{"Row":2,"place":4,"free":true},{"Row":2,"place":5,"free":true},{"Row":2,"place":6,"free":true},{"Row":2,"place":7,"free":true},{"Row":2,"place":8,"free":true},{"Row":2,"place":9,"free":true},{"Row":2,"place":10,"free":true},{"Row":3,"place":1,"free":true},{"Row":3,"place":2,"free":true},{"Row":3,"place":3,"free":true},{"Row":3,"place":4,"free":true},{"Row":3,"place":5,"free":true},{"Row":3,"place":6,"free":true},{"Row":3,"place":7,"free":true},{"Row":3,"place":8,"free":true},{"Row":3,"place":9,"free":true},{"Row":3,"place":10,"free":true},{"Row":4,"place":1,"free":true},{"Row":4,"place":2,"free":true},{"Row":4,"place":3,"free":true},{"Row":4,"place":4,"free":true},{"Row":4,"place":5,"free":true},{"Row":4,"place":6,"free":true},{"Row":4,"place":7,"free":true},{"Row":4,"place":8,"free":true},{"Row":4,"place":9,"free":true},{"Row":4,"place":10,"free":true},{"Row":5,"place":1,"free":true},{"Row":5,"place":2,"free":true},{"Row":5,"place":3,"free":true},{"Row":5,"place":4,"free":true},{"Row":5,"place":5,"free":true},{"Row":5,"place":6,"free":true},{"Row":5,"place":7,"free":true},{"Row":5,"place":8,"free":true},{"Row":5,"place":9,"free":true},{"Row":5,"place":10,"free":true}]}', 50);


